FROM node:20-slim AS base

ARG service
ENV USERS_SERVER_PORT=3000

WORKDIR /app
RUN corepack enable
RUN corepack use pnpm
COPY pnpm-*.yaml .
COPY tsconfig*.json .
COPY libs libs

WORKDIR /app/services/${service}
COPY services/${service} .
RUN pnpm i
RUN pnpm build

CMD [ "pnpm", "start" ]